config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end
  root 'posts#fake_gallery' # To deal with kaminari bug

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'browse', to: 'posts#browse', as: :browse_posts
  get 'gallery', to: 'posts#gallery', as: :gallery
  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

  scope '/u' do
    get ':user_name', to: 'profiles#show', as: :profile
    get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
    patch ':user_name/edit', to: 'profiles#update', as: :update_profile

    post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
    post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_user
  before_action :owned_profile, only: [:edit, :update]

  def show
    @posts = @user.posts.order("created_at DESC")
  end

  def edit
  end

  def update
    if @user.update(profile_params)
      flash[:success] = 'Your profile has been updated.'
      redirect_to profile_path(@user.user_name)
    else
      @user.errors.full_messages
      flash.now[:error] = @user.errors.full_messages
      render 'edit'
    end
  end

  private
    def profile_params
      params.require(:user).permit(:avatar, :bio)
    end

    def find_user
      @user = User.find_by(user_name: params[:user_name])
    end

    def owned_profile
      @user = User.find_by(user_name: params[:user_name])
      unless current_user == @user
        flash[:alert] = "That profile doesn't belong to you!"
        redirect_to root_path
      end
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def current_user_is_following(current_user_id, followed_user_id)
    relationship = Follow.find_by(follower_id: current_user_id, following_id: followed_user_id)
    #return true if relationship
  end
end

app/views/profiles/edit.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_for @user, url: { action: "update" }, html: { multipart: true } do |f|
          .row
            .col-md-12
              .form-group.text-center
                %h4 Change your profile image:
                .img-circle
                  = profile_avatar_select(@user)
                = f.file_field :avatar, onChange: 'loadFile(event)'
          .row
            .col-md-12
              .form-group.text-center
                %h4 Update your bio:
                = f.text_area :bio, label: false, rows: 4
          .form-group.text-center
            = f.submit "Update Profile", class: 'btn btn-success'

app/views/profiles/show.html.haml
.posts-wrapper
  .row.profile-header
    .col-xs-10.col-xs-offset-1.col-md-6.col-md-offset-0
      .img-circle
        = profile_avatar_select(@user)
    .col-xs-10.col-xs-offset-1.col-md-6.col-md-offset-0
      .user-name-and-follow
        %h3.profile-user-name
          = @user.user_name
        %span
          - if @user == current_user
            = link_to 'Edit Profile', edit_profile_path(@user.user_name),
                                      class: 'btn edit-button'
          - else
            - if current_user_is_following(current_user.id, @user.id)
              = link_to 'Following', unfollow_user_path,
                                     class: 'btn unfollow-button',
                                     id: 'unfollow-button',
                                     method: :post,
                                     remote: true
            - else
              = link_to 'Follow', follow_user_path,
                                  class: 'btn follow-button',
                                  id: 'follow-button',
                                  method: :post,
                                  remote: true
      %p.profile-bio
        = @user.bio
      .user-statistics
        %p
          = pluralize @user.posts.count, 'post'
        %p
          = pluralize @user.followers.count, 'follower'
        %p
          = pluralize @user.followings.count, 'following'

#posts
  .posts-wrapper
    = render @posts