config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end
  root 'posts#fake_gallery' # To deal with kaminari bug

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'browse', to: 'posts#browse', as: :browse_posts
  get 'gallery', to: 'posts#gallery', as: :gallery
  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

  scope '/u' do
    get ':user_name', to: 'profiles#show', as: :profile
    get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
    patch ':user_name/edit', to: 'profiles#update', as: :update_profile

    post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
    post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  end

end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_votable

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates :image, presence: true
  validates :caption, presence: true, length: { maximum: 300 }
  validates :user_id, presence: true

  scope :of_followed_users, -> (following_users) { where(user_id: following_users) }
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:gallery, :fake_gallery]
  before_action :find_post, only: [:show, :edit, :update, :destroy, :like, :unlike]
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = current_user.feed.order("created_at DESC").page(params[:page])
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post has been created."
      redirect_to posts_path
    else
      flash.now[:alert] = "Post can't be created."
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post has been updated."
      redirect_to @post
    else
      flash.now[:alert] = "Post can't be updated."
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post has been deleted."
    redirect_to posts_path
  end

  def like
    if @post.liked_by current_user
      create_notification(@post)
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def unlike
    if @post.unliked_by current_user
      respond_to do |format|
        format.html { redirect_to :back }
        format.js
      end
    end
  end

  def browse
    @posts = Post.all.order('created_at DESC').page params[:page]
  end

  def gallery
    @posts = Post.all.order('created_at DESC').page(params[:page]).per(20)
  end

  # To deal with kaminari bug
  def fake_gallery
    redirect_to gallery_path
  end

  private
    def post_params
      params.require(:post).permit(:caption, :image)
    end

    def find_post
      @post = Post.find(params[:id])
    end

    def owned_post
      unless current_user == Post.find(params[:id]).user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end

    def create_notification(post)
      return if post.user.id == current_user.id
      Notification.create(user_id: post.user.id,
                          notified_by_id: current_user.id,
                          post_id: post.id,
                          identifier: post.id,
                          notice_type: 'like',
                          read: false)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
  def display_likes(post)
    votes = post.votes_for.up.by_type(User)
    return list_likers(votes) if votes.size <= 8
    count_likers(votes)
  end

  def liked_post(post)
    ht = 'glyphicon-heart'
    path = unlike_post_path(post.id)
    unless current_user.voted_for? post
      ht += '-empty'
      path = like_post_path(post.id)
    end
    link_to '', path, remote: true, id: "like_#{post.id}", class: "like glyphicon #{ht}"
  end

  private

    def list_likers(votes)
      user_names = []
      unless votes.blank?
        votes.voters.each do |voter|
          user_names.push(link_to voter.user_name,
                                  profile_path(voter.user_name),
                                  class: 'user-name')
        end
        user_names.to_sentence.html_safe + like_plural(votes)
      end
    end

    def count_likers(votes)
      vote_count = votes.size
      vote_count.to_s + ' likes'
    end

    def like_plural(votes)
      votes.count > 1 ? ' like this' : ' likes this'
    end
  end

app/views/posts/_form.html.haml
.posts-wrapper
  .post
    .post-body
      .image-wrap
        = form_image_select(@post)
        = simple_form_for @post, html: { multipart: true } do |f|
          .row
            .col-md-12.text-center
              = f.error_notification
          .container-fluid
            .form-group.text-center
              %h4 Upload an image (this is required):
              = f.input :image, label: false, input_html: { onChange: 'loadFile(event)' }
            .form-group.text-center
              = f.input :caption, label: false, placeholder: 'Add your caption'
            .form-group.text-center
              = f.button :submit, class: 'btn-success btn-block'

app/views/posts/_likes.html.haml
.likes{id: "likes_#{post.id}"}
  = display_likes post

app/views/posts/_post.html.haml
.post
  .post-head
    .thumb-img
    .user-name
      = link_to post.user.user_name, profile_path(post.user.user_name)
    .time-ago
      = time_ago_in_words post.created_at
      ago
  .image.center-block
    = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
  .post-bottom
    = render 'posts/likes', post: post
    .caption
      .user-name
        = link_to post.user.user_name, profile_path(post.user.user_name)
      = post.caption
    .comments{id: "comments_#{post.id}"}
      - if post.comments.any?
        .paginator{id: "#comments-paginator-#{post.id}"}
        - unless post.comments.count <= 4
          = link_to "View all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments', data: {post_id: "#{post.id}", type: "html"}
        = render post.comments.last(4), post: post
  .comment-like-form.row
    .col-xs-2.col-sm-1
      = liked_post post
    .comment-form.col-xs-10.col-sm-11
      = form_for [post, post.comments.new], html: {id: "new_comment_#{post.id}"}, remote: true do |f|
        = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"
        = f.submit class: "comment-submit-button", id: "submit_comment_#{post.id}"

app/views/posts/_post_dashboard.html.haml
#posts
  .posts-wrapper
    = render @posts

- np = link_to_next_page @posts, 'LOAD MORE', id: 'load_more', remote: true
- unless np.blank?
  #paginator.text-center
    = np

app/views/posts/browse.html.haml
= render 'post_dashboard', posts: @posts

app/views/posts/browse.js.erb
$('.posts-wrapper').append("<%= escape_javascript(render @posts)%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/edit.html.haml
= render 'form'
.text-center.edit-links
  = link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "Cancel", posts_path

app/views/posts/gallery.html.haml
-# unless user_signed_in?
  .jumbotron.center
    %h1
      Welcome to
      %span.title Beautifulgram
    %p
      = link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg"
      = link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg"

.gallery.transitions-enabled.infinite-scroll.container
  - @posts.each do |post|
    .gallery-box.post
      .image.center-block
        = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
      .post-bottom
        .user-name
          = link_to post.user.user_name, profile_path(post.user.user_name)
        = post.caption

- np = link_to_next_page @posts, 'LOAD MORE', id: 'load_more'
- unless np.blank?
  #paginator.text-center{style: 'display: none'}
    = np

app/views/posts/index.html.haml
= render 'post_dashboard', posts: @posts

app/views/posts/index.js.erb
$('.posts-wrapper').append("<%= escape_javascript(render @posts)%>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'LOAD MORE', remote: true, id: 'load_more'))%>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');
$("#like_<%= @post.id %>").attr("href", "<%= unlike_post_path @post.id %>");
$("#likes_<%= @post.id %>").replaceWith("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");

app/views/posts/new.html.haml
= render 'form'

app/views/posts/show.html.haml
.posts-wrapper
  = render 'post', post: @post
- if @post.user.id == current_user.id
  .text-center.edit-links
    = link_to "Edit Post", edit_post_path(@post)

app/views/posts/unlike.js.erb
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');
$("#like_<%= @post.id %>").attr("href", "<%= like_post_path @post.id %>");
$("#likes_<%= @post.id %>").replaceWith("<%= j (render partial: 'posts/likes', locals: { post: @post} ) %>");