config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }

  authenticated :user do
    root 'posts#index', as: :authenticated_root
  end
  root 'posts#fake_gallery' # To deal with kaminari bug

  resources :posts do
    resources :comments
    member do
      get 'like'
      get 'unlike'
    end
  end

  get 'browse', to: 'posts#browse', as: :browse_posts
  get 'gallery', to: 'posts#gallery', as: :gallery
  get 'notifications', to: 'notifications#index'
  get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

  scope '/u' do
    get ':user_name', to: 'profiles#show', as: :profile
    get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
    patch ':user_name/edit', to: 'profiles#update', as: :update_profile

    post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user
    post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user
  end

end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Beautifulgram", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = render 'notifications/notification_dropdown'
          %li
            = link_to "New Post", new_post_path
          %li
            = link_to "My Profile", profile_path(current_user.user_name)
          %li
            = link_to "All Posts", browse_posts_path
          %li
            = link_to "Gallery", gallery_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Beautifulgram
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1.0, maximum-scale=1.0" }
  %body
    = render 'layouts/navbar'

    - flash.each do |name, msg|
      = content_tag :div, msg, class: [:alert, alert_for(name)]
    = yield